version: '3.8'

services: 
    postgresql:
        image: postgres:13-alpine
        ports:
        - '5432:5432'
        container_name: 'pgsql'
        restart: always
        volumes:
        - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: toor

    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080
        container_name: 'adminer'

volumes:
    pgdata: